version: '3.5'

services:
  fambook-angular:
    image: fambook-angular-i
    container_name: fambook-angular
    build: 
      context: ./src/Fambook-angular
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  fambook-userservice:
    image: fambook-userservice-i
    container_name: fambook-userservice
    build:
      context: ./src/services/Fambook.UserService
      dockerfile: Dockerfile
    ports:
      - "51010:80"
    environment:
      ENERGIESTUCK_ENERGIESERVICE_DB: 'Server=.;Database=Uplift;Trusted_Connection=True;MultipleActiveResultSets=true'