apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "fambook"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "fambook"
    spec:
      containers:
        - name: "fambook"
          image: "fambookfrontend.azurecr.io/fambook"
          ports:
          - containerPort: 80